---

- name: Copying keepalived.conf
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  notify: restart keepalived

- name: Enable keepalived to be started at boot
  service: name=keepalived enabled=yes state=started